- name: Ensure GlusterFS related packages are installed
  yum: name="{{ item }}"
  with_items:
    - centos-release-gluster38
    - glusterfs
    - gluster-cli
    - glusterfs-server

- name: Ensure GlusterFS related services are started
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - glusterd

- name: Ensure sdb partion is created
  command: pvcreate /dev/sdb

- name: Ensure volume group is created
  command: vgcreate vg_gluster /dev/sdb

- name: Ensure logical volume is created
  command: lvcreate -L 5G -n brick1 vg_gluster

- name: create gluster volume
  gluster_volume:
    state: present
    name: glustervol1
    bricks: /bricks/brick1/g1
    rebalance: yes
    cluster:
      - 192.0.2.10
      - 192.0.2.11
  run_once: true

- name: Ensure data directory is created
  file: path=/data/brick state=directory

- name: Probe storage master
  command: gluster peer probe {{ storage_master }}

- name: Probe storage nodes
  command: gluster peer probe {{ item }}
  with_items: {{ storage_nodes }}
