- name: Ensure Gluster related packages are installed
  yum: name={{ item }}
  with_items:
    - centos-release-gluster39

- name: Ensure Gluster related packages are installed
  yum: name={{ item }}
  with_items:
    - glusterfs
    - glusterfs-server

- name: Ensure Gluster related services are started
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - glusterd

- name: Create brick directory
  file: name=/data/brick state=directory

- name: Create mount directory
  file: name=/mount/k8s/{{ item }} state=directory
  with_items: "{{ gluster_volumes }}"

- name: Probe storage nodes
  command: gluster peer probe {{ item }}
  with_items:
    - 192.168.88.88
    # - 192.168.88.3
  ignore_errors: true

- name: Create Gluster volumes
  gluster_volume:
    state: present
    name: "{{ item }}"
    # replicas: 2
    bricks: /data/brick/{{ item }}1,/data/brick/{{ item }}2
    force: true
    rebalance: true
    cluster:
      - 192.168.88.88
      # - 192.168.88.3
  run_once: true
  with_items: "{{ gluster_volumes }}"

- name: Start Gluster volumes
  gluster_volume:
    state: started
    name: "{{ item }}"
  with_items: "{{ gluster_volumes }}"

- name: Mount Gluster volumes
  mount:
    name: /mnt/k8s/{{ item }}
    src: 192.168.88.88:{{ item }}
    fstype: glusterfs
    boot: true
    state: mounted
  with_items: "{{ gluster_volumes }}"

# sudo yum install -y centos-release-gluster39
# sudo yum install -y glusterfs glusterfs-server
# sudo mkdir -p /data/brick
# sudo systemctl enable glusterd && sudo systemctl start glusterd
