---
- hosts: gluster_nodes
  become: true
  vars:
    domain: 192.168.88.88.nip.io
    network_interface: eth0
    gluster_volumes:
      - influxdb-volume
      - grafana-volume
      - gogs-volume
      - jenkins-volume
  roles:
    - glusterfs
    - telegraf

- hosts: k8s_master
  become: true
  vars:
    domain: 192.168.88.88.nip.io
    network_interface: eth0
  roles:
    - docker
    - kubernetes
    - telegraf
    - nginx
