- name: Ensure Kubernetes repo is enabled
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg  https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: no
    repo_gpgcheck: no

- name: Ensure Kubernetes related packages are installed
  yum: name="{{ item }}"
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Ensure SELinux is in Permissive mode
  selinux: policy=targeted state=permissive

- name: Ensure Kubernetes related services are started
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - kubelet

- name: Ensure 10-kubeadm.conf is fixed
  file: src=kubeadm.conf dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Init Kubernetes
  command: kubeadm init --apiserver-advertise-address {{ hostvars[groups['k8s_master'][0]]['ansible_default_ipv4']['address'] }}

- name: Install Kubernetes network add-on
  command: kubectl apply -f https://git.io/weave-kube-1.6

- name: Ensure master is available for running pods
  command: kubectl taint nodes --all node-role.kubernetes.io/master-

- name: Ensure Kubernetes resources directory exist
  file: name=/etc/k8s state=directory

- name: Copy Kubernetes resources
  template: src={{ item }} dest=/etc/k8s/{{ item }}
  with_items:
    - gluster-endpoint.yml
    - traefik.yml
    - influxdb.yml
    - grafana.yml
    - gogs.yml
    - jenkins.yml
    - default-backend.yml

- name: Create Kubernetes resources
  command: "{{ item }} chdir=/etc/k8s/"
  with_items:
    - kubectl apply -f gluster-endpoint.yml
    - kubectl apply -f traefik.yml
    - kubectl apply -f influxdb.yml
    - kubectl apply -f grafana.yml
    - kubectl apply -f gogs.yml
    - kubectl apply -f jenkins.yml
    - kubectl apply -f default-backend.yml
