apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: http
