apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster 
subsets:
{% for host in groups['gluster_nodes'] %}
  - addresses:
      - ip: "{{ hostvars[host]['ansible_default_ipv4']['address'] }}"
    ports:
      - port: 1
{% endfor %}
