apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster 
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster 
subsets:
{% for host in groups['gluster_nodes'] %}
  - addresses:
      - ip: "{{ hostvars[host]['ansible_' + network_interface]['ipv4']['address'] }}"
    ports:
      - port: 1
{% endfor %}
