apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: gluster-cluster
    path: gogs-volume
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - name: gogs
        image: gogs/gogs
        volumeMounts:
        - name: gogs-volume
          mountPath: /data
        ports:
        - containerPort: 22
        - containerPort: 3000
      volumes:
      - name: gogs-volume
        persistentVolumeClaim:
          claimName: gogs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: gogs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
spec:
  rules:
  - host: gogs.{{ domain }}
    http:
      paths:
      - backend:
          serviceName: gogs
          servicePort: http
