apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        volumeMounts:
        - name: influxdb-volume
          mountPath: /var/lib/influxdb
        ports:
        - containerPort: 8086
      volumes:
      - name: influxdb-volume
        hostPath:
          path: /var/k8s/influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
    - name: api
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: influxdb
spec:
  rules:
  - host: influxdb.{{ domain }}
    http:
      paths:
      - backend:
          serviceName: influxdb
          servicePort: api
