apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: gluster-cluster
    path: influxdb-volume
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        volumeMounts:
        - name: influxdb-volume
          mountPath: /var/lib/influxdb
        ports:
        - containerPort: 8086
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
    - name: api
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: influxdb
spec:
  rules:
  - host: influxdb.{{ domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: influxdb
          servicePort: api
